### ISSUE TITLE
SSL connection could not be established 

### ISSUE THREAD

**Issue by rkirandas** [hyperledger-aries/aries-mobile-agent-xamarin#63]
Ran the mediator agent using ngrok url and configured the xamarin's endoint to ngork url and on clicking create wallet getting error 'Failed to create wallet.The SSL connection could not be established see inner exception'

**Comment by x0axz** [comment]
What is the Ngrok URL? 
What is the Agent's `EndpointUri` in `Starup.cs` and the `applicationUrl in `Properties/launchSettings.json`?

**Comment by rkirandas** [comment]
As per mentioned in video [(https://www.loom.com/share/5c52c185673046b688bdd1ef7d280185)](url) . I created an ngrok public uri based on 5000 port and modified it in the Mediator Agent's EndpointUri in Starup.cs (didnt do anything on Properties/launchSettings.json) and also changed the options.EndpointUri to the same in Aries MAX.

**Comment by rkirandas** [comment]
@x0axz  

When I used local port ( Opened a mediator in wifi network and opened that port in firewall  do that the app is in same network and can access mediator ) instead I got an error in Mobile App side  Cannot Create Wallet - Connection Refused 


What are the actual steps to setup mobile wallet. Any help would be appreciated

**Comment by rkirandas** [comment]
@x0axz 

Were you able setup the Aries Max without any issue? 
If yes
Can you give me step by step walkthrough.

**Comment by softronsts** [comment]
I am having the same issue. Closed this issue based on what resolution?

**Comment by rkirandas** [comment]
> I am having the same issue. Closed this issue based on what resolution?

I switched to https://github.com/hyperledger/aries-mobile-agent-react-native. Looks like the issues aren't tracked anymore
